# Example: Position Verification in GitHub Actions
#
# This example shows how to integrate verify_positions.py into your CI/CD workflow
# Add this as a step in .github/workflows/daily-trading.yml or create a standalone workflow

name: Position Verification Example

on:
  # Run after trading execution
  workflow_run:
    workflows: ["Daily Trading Execution"]
    types:
      - completed

  # Also allow manual triggers
  workflow_dispatch:

jobs:
  verify-positions:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir alpaca-py python-dotenv

      - name: Verify Positions Match Alpaca
        id: verify
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        run: |
          python3 scripts/verify_positions.py

      - name: Check Verification Results
        if: steps.verify.outputs.positions_match == 'false'
        run: |
          echo "::error::Position verification failed!"
          echo "::error::Found ${{ steps.verify.outputs.discrepancy_count }} discrepancies"
          echo "::error::Review the verification output above for details"
          exit 1

      - name: Post Success Comment (Optional)
        if: steps.verify.outputs.positions_match == 'true'
        run: |
          echo "✅ Position verification passed - all positions match Alpaca"

      # Optional: Auto-fix discrepancies (use with caution)
      - name: Auto-Fix Discrepancies (Optional)
        if: steps.verify.outputs.positions_match == 'false' && github.event_name == 'workflow_dispatch'
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        run: |
          echo "⚠️ Auto-fixing discrepancies..."
          python3 scripts/reconcile_positions.py --fix

      # Optional: Upload reconciliation report as artifact
      - name: Upload Reconciliation Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reconciliation-report
          path: data/reconciliation/*.json
          if-no-files-found: ignore
          retention-days: 30

---

# Simpler Integration: Add to Existing Daily Trading Workflow

# Add this step to .github/workflows/daily-trading.yml after trade execution:

      # ... existing trading steps ...

      - name: Verify Positions
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        run: |
          python3 scripts/verify_positions.py

      # ... rest of workflow ...

---

# Production-Ready Integration with Slack Alerts

      - name: Verify Positions Match
        id: verify_positions
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
        run: |
          python3 scripts/verify_positions.py
        continue-on-error: true

      - name: Alert on Discrepancy
        if: steps.verify_positions.outputs.positions_match == 'false'
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -X POST $SLACK_WEBHOOK -H 'Content-Type: application/json' -d '{
            "text": "🚨 Position Verification Failed",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Position verification detected ${{ steps.verify_positions.outputs.discrepancy_count }} discrepancies*\n\nLocal state is out of sync with Alpaca API."
                }
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Workflow"
                    },
                    "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
          }'
          exit 1
