#!/usr/bin/env python3
"""
Test dashboard output completeness and correctness.

Validates that generated dashboards contain all required sections.
This prevents regressions where sections are accidentally removed.
"""

import json
import sys
import tempfile
from datetime import date, timedelta
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))


def create_test_data(tmpdir: Path):
    """Create minimal test data files."""
    data_dir = tmpdir / "data"
    data_dir.mkdir()

    # Create performance log
    perf_log = []
    base_equity = 100000.0
    for i in range(5):
        equity = base_equity + (i * 100)
        perf_log.append(
            {
                "date": (date.today() - timedelta(days=5 - i)).isoformat(),
                "equity": equity,
                "pl": equity - base_equity,
                "pl_pct": (equity - base_equity) / base_equity,
            }
        )

    with open(data_dir / "performance_log.json", "w") as f:
        json.dump(perf_log, f)

    # Create system_state.json
    with open(data_dir / "system_state.json", "w") as f:
        json.dump(
            {
                "account": {
                    "current_equity": perf_log[-1]["equity"],
                    "total_pl": perf_log[-1]["pl"],
                    "total_pl_pct": perf_log[-1]["pl_pct"],
                },
                "performance": {
                    "win_rate": 0.5,
                    "total_trades": 10,
                    "winning_trades": 5,
                    "losing_trades": 5,
                    "closed_trades": [],
                },
                "challenge": {
                    "start_date": (date.today() - timedelta(days=5)).isoformat(),
                    "current_day": 5,
                    "total_days": 90,
                    "phase": "R&D Phase - Month 1 (Days 1-30)",
                },
                "automation": {
                    "workflow_status": "OPERATIONAL",
                    "last_successful_execution": date.today().isoformat(),
                },
            },
            f,
        )

    # Create challenge_start.json
    with open(data_dir / "challenge_start.json", "w") as f:
        json.dump(
            {
                "start_date": (date.today() - timedelta(days=5)).isoformat(),
                "starting_balance": base_equity,
            },
            f,
        )

    # Create today's trades file (empty)
    today_trades_file = data_dir / f"trades_{date.today().isoformat()}.json"
    with open(today_trades_file, "w") as f:
        json.dump([], f)

    return data_dir


def test_dashboard_has_required_sections(dashboard_content: str, script_name: str):
    """Test that dashboard contains all required sections."""
    required_sections = [
        ("Today's Performance", "📅 Today's Performance"),
        ("North Star Goal", "🎯 North Star Goal"),
    ]

    missing_sections = []
    for section_name, section_marker in required_sections:
        if section_marker not in dashboard_content:
            missing_sections.append(f"{section_name} (looking for: {section_marker})")

    if missing_sections:
        raise AssertionError(
            f"Dashboard generated by {script_name} is missing required sections:\n"
            + "\n".join(f"  - {s}" for s in missing_sections)
            + f"\n\nDashboard preview (first 500 chars):\n{dashboard_content[:500]}"
        )


def test_world_class_dashboard():
    """Test generate_world_class_dashboard.py output."""
    import os

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir_path = Path(tmpdir)
        create_test_data(tmpdir_path)

        # Temporarily override DATA_DIR
        original_cwd = os.getcwd()
        try:
            os.chdir(tmpdir_path)

            # Import and generate dashboard
            from scripts.generate_world_class_dashboard import (
                generate_world_class_dashboard,
            )

            dashboard = generate_world_class_dashboard()

            # Validate required sections
            test_dashboard_has_required_sections(dashboard, "generate_world_class_dashboard.py")

            print("✅ generate_world_class_dashboard.py: PASSED")
            return True

        finally:
            os.chdir(original_cwd)


def test_world_class_dashboard_enhanced():
    """Test generate_world_class_dashboard_enhanced.py output."""
    import os

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir_path = Path(tmpdir)
        create_test_data(tmpdir_path)

        original_cwd = os.getcwd()
        try:
            os.chdir(tmpdir_path)

            from scripts.generate_world_class_dashboard_enhanced import (
                generate_world_class_dashboard,
            )

            dashboard = generate_world_class_dashboard()

            test_dashboard_has_required_sections(
                dashboard, "generate_world_class_dashboard_enhanced.py"
            )

            print("✅ generate_world_class_dashboard_enhanced.py: PASSED")
            return True

        finally:
            os.chdir(original_cwd)


def test_progress_dashboard():
    """Test generate_progress_dashboard.py output."""
    import os

    with tempfile.TemporaryDirectory() as tmpdir:
        tmpdir_path = Path(tmpdir)
        create_test_data(tmpdir_path)

        original_cwd = os.getcwd()
        try:
            os.chdir(tmpdir_path)

            from scripts.generate_progress_dashboard import generate_dashboard

            dashboard = generate_dashboard()

            test_dashboard_has_required_sections(dashboard, "generate_progress_dashboard.py")

            print("✅ generate_progress_dashboard.py: PASSED")
            return True

        finally:
            os.chdir(original_cwd)


def run_tests():
    """Run all dashboard output tests."""
    print("=" * 70)
    print("Testing Dashboard Output Completeness")
    print("=" * 70)
    print()

    failures = []

    # Test each dashboard generator
    try:
        test_world_class_dashboard()
    except Exception as e:
        print(f"❌ generate_world_class_dashboard.py: FAILED - {e}")
        failures.append("generate_world_class_dashboard.py")

    try:
        test_world_class_dashboard_enhanced()
    except Exception as e:
        print(f"❌ generate_world_class_dashboard_enhanced.py: FAILED - {e}")
        failures.append("generate_world_class_dashboard_enhanced.py")

    try:
        test_progress_dashboard()
    except Exception as e:
        print(f"❌ generate_progress_dashboard.py: FAILED - {e}")
        failures.append("generate_progress_dashboard.py")

    print()
    print("=" * 70)
    if failures:
        print(f"❌ {len(failures)} test(s) failed:")
        for f in failures:
            print(f"   - {f}")
        return 1
    else:
        print("✅ All dashboard output tests passed!")
        return 0
    print("=" * 70)


if __name__ == "__main__":
    sys.exit(run_tests())
