import json
import logging
import sys
from pathlib import Path
from typing import Dict, Any, Optional
from datetime import datetime

# Add repo root to path for imports
REPO_ROOT = Path(__file__).parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.safety.handoff_governance import (
    append_handoff_audit_record,
    build_delegation_contract,
    infer_risk_tier,
    validate_delegation_contract,
)
from src.safety.trading_policy_drift import (
    DEFAULT_POLICY_DOC_PATHS,
    collect_trading_policy_ab_metrics,
    write_trading_policy_ab_metrics,
)

REQUIRED_AGENTS_SECTIONS = (
    "requesting_agent",
    "target_agent", 
    "task_description",
    "risk_assessment",
    "permissions_requested"
)

HANDOFF_DOCS_DIR = REPO_ROOT / "docs" / "agent_handoffs"


class GateStepResult:
    """Result of a gate step execution."""

    def __init__(self, success: bool, message: str, data: Dict[str, Any] = None):
        self.success = success
        self.message = message
        self.data = data or {}


class GateReport:
    """Report generated by the agent handoff gate process."""

    def __init__(self, status: str, message: str, details: Dict[str, Any] = None):
        self.status = status
        self.message = message
        self.details = details or {}


def validate_handoff_document(doc_path: Path) -> GateStepResult:
    """
    Validate that a handoff document contains all required sections.

    Args:
        doc_path: Path to the handoff document

    Returns:
        GateStepResult with validation status
    """
    if not doc_path.exists():
        return GateStepResult(
            success=False,
            message=f"Handoff document not found: {doc_path}"
        )

    try:
        content = doc_path.read_text()
        missing_sections = []
        
        for section in REQUIRED_AGENTS_SECTIONS:
            if section not in content.lower():
                missing_sections.append(section)
        
        if missing_sections:
            return GateStepResult(
                success=False,
                message=f"Missing required sections: {', '.join(missing_sections)}"
            )
        
        return GateStepResult(
            success=True,
            message="Document validation passed"
        )
    
    except Exception as e:
        return GateStepResult(
            success=False,
            message=f"Error reading document: {str(e)}"
        )


def assess_risk_tier(handoff_data: Dict[str, Any]) -> GateStepResult:
    """
    Assess the risk tier for the handoff request.
    
    Args:
        handoff_data: Parsed handoff request data
        
    Returns:
        GateStepResult with risk assessment
    """
    try:
        risk_tier = infer_risk_tier(handoff_data)
        return GateStepResult(
            success=True,
            message=f"Risk tier assessed: {risk_tier}",
            data={"risk_tier": risk_tier}
        )
    except Exception as e:
        return GateStepResult(
            success=False,
            message=f"Risk assessment failed: {str(e)}"
        )


def check_policy_drift() -> GateStepResult:
    """
    Check for trading policy drift.
    
    Returns:
        GateStepResult with drift check status
    """
    try:
        metrics = collect_trading_policy_ab_metrics(DEFAULT_POLICY_DOC_PATHS)
        
        # Check if there's significant drift
        if metrics.get("drift_detected", False):
            return GateStepResult(
                success=False,
                message="Trading policy drift detected",
                data=metrics
            )
        
        return GateStepResult(
            success=True,
            message="No policy drift detected",
            data=metrics
        )
    except Exception as e:
        return GateStepResult(
            success=False,
            message=f"Policy drift check failed: {str(e)}"
        )


def create_delegation_contract(handoff_data: Dict[str, Any]) -> GateStepResult:
    """
    Create a delegation contract for the handoff.
    
    Args:
        handoff_data: Parsed handoff request data
        
    Returns:
        GateStepResult with contract creation status
    """
    try:
        contract = build_delegation_contract(handoff_data)
        
        # Validate the contract
        validation_result = validate_delegation_contract(contract)
        
        if not validation_result.get("valid", False):
            return GateStepResult(
                success=False,
                message=f"Contract validation failed: {validation_result.get('errors', [])}"
            )
        
        return GateStepResult(
            success=True,
            message="Delegation contract created successfully",
            data={"contract": contract}
        )
    except Exception as e:
        return GateStepResult(
            success=False,
            message=f"Contract creation failed: {str(e)}"
        )


def process_handoff_gate(handoff_doc_path: str) -> GateReport:
    """
    Process a handoff through the agent handoff gate.
    
    Args:
        handoff_doc_path: Path to the handoff document
        
    Returns:
        GateReport with overall process status
    """
    doc_path = Path(handoff_doc_path)
    
    # Step 1: Validate document structure
    validation_result = validate_handoff_document(doc_path)
    if not validation_result.success:
        return GateReport(
            status="REJECTED",
            message=f"Document validation failed: {validation_result.message}"
        )
    
    # Parse handoff data (simplified for this example)
    try:
        handoff_data = {
            "document_path": str(doc_path),
            "timestamp": datetime.now().isoformat(),
            "requesting_agent": "unknown",  # Would be parsed from document
            "target_agent": "unknown"       # Would be parsed from document
        }
    except Exception as e:
        return GateReport(
            status="ERROR",
            message=f"Failed to parse handoff data: {str(e)}"
        )
    
    # Step 2: Assess risk tier
    risk_result = assess_risk_tier(handoff_data)
    if not risk_result.success:
        return GateReport(
            status="ERROR",
            message=f"Risk assessment failed: {risk_result.message}"
        )
    
    # Step 3: Check for policy drift
    drift_result = check_policy_drift()
    if not drift_result.success:
        return GateReport(
            status="REJECTED",
            message=f"Policy drift detected: {drift_result.message}",
            details=drift_result.data
        )
    
    # Step 4: Create delegation contract
    contract_result = create_delegation_contract(handoff_data)
    if not contract_result.success:
        return GateReport(
            status="ERROR",
            message=f"Contract creation failed: {contract_result.message}"
        )
    
    # Step 5: Record audit trail
    try:
        audit_data = {
            "handoff_data": handoff_data,
            "risk_tier": risk_result.data.get("risk_tier"),
            "contract": contract_result.data.get("contract"),
            "timestamp": datetime.now().isoformat()
        }
        append_handoff_audit_record(audit_data)
    except Exception as e:
        return GateReport(
            status="WARNING",
            message=f"Handoff approved but audit recording failed: {str(e)}",
            details={"contract": contract_result.data.get("contract")}
        )
    
    return GateReport(
        status="APPROVED",
        message="Handoff processed successfully",
        details={
            "risk_tier": risk_result.data.get("risk_tier"),
            "contract": contract_result.data.get("contract")
        }
    )


def main():
    """Main entry point for the agent handoff gate."""
    if len(sys.argv) != 2:
        print("Usage: python agent_handoff_gate.py <handoff_doc_path>")
        sys.exit(1)
    
    handoff_doc_path = sys.argv[1]
    
    # Set up logging
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s - %(message)s'
    )
    
    logger = logging.getLogger(__name__)
    logger.info(f"Processing handoff gate for: {handoff_doc_path}")
    
    # Process the handoff
    report = process_handoff_gate(handoff_doc_path)
    
    # Output results
    print(f"Status: {report.status}")
    print(f"Message: {report.message}")
    
    if report.details:
        print("Details:")
        print(json.dumps(report.details, indent=2))
    
    # Exit with appropriate code
    if report.status == "APPROVED":
        sys.exit(0)
    elif report.status in ["REJECTED", "ERROR"]:
        sys.exit(1)
    else:  # WARNING
        sys.exit(0)


if __name__ == "__main__":
    main()