#!/usr/bin/env python3

import argparse
import sys
from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime
import logging

# Add the repo root to Python path for imports
REPO_ROOT = Path(__file__).parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.safety.handoff_governance import (
    append_handoff_audit_record,
    build_delegation_contract,
    infer_risk_tier,
    validate_delegation_contract,
)
from src.safety.trading_policy_drift import (
    DEFAULT_POLICY_DOC_PATHS,
    collect_trading_policy_ab_metrics,
    write_trading_policy_ab_metrics,
)

REQUIRED_AGENTS_SECTIONS = (
    "## 🤖 Agent Handoff",
    "## 📊 Key Metrics",
    "## 🔄 Agent Transition",
    "## ⚠️ Risk Assessment",
    "## 🎯 Next Steps"
)


class GateReport:
    """Report generated by the agent handoff gate process."""
    
    def __init__(self, status: str, message: str, details: Dict[str, Any] = None):
        self.status = status
        self.message = message
        self.details = details or {}
        self.timestamp = datetime.now()


def validate_handoff_document(doc_path: Path) -> Dict[str, Any]:
    """
    Validate that a handoff document contains all required sections.
    
    Args:
        doc_path: Path to the handoff document
        
    Returns:
        Dict containing validation results
    """
    if not doc_path.exists():
        return {
            "valid": False,
            "missing_sections": list(REQUIRED_AGENTS_SECTIONS),
            "error": f"Document not found: {doc_path}"
        }

    try:
        content = doc_path.read_text(encoding='utf-8')
    except Exception as e:
        return {
            "valid": False,
            "missing_sections": list(REQUIRED_AGENTS_SECTIONS),
            "error": f"Failed to read document: {e}"
        }

    missing_sections = []
    for section in REQUIRED_AGENTS_SECTIONS:
        if section not in content:
            missing_sections.append(section)

    return {
        "valid": len(missing_sections) == 0,
        "missing_sections": missing_sections,
        "error": None
    }


def run_agent_handoff_gate(
    handoff_doc_path: str,
    delegation_target: str = "trading_agent",
    risk_tier: Optional[str] = None
) -> GateReport:
    """
    Main gate function that validates agent handoff documentation and processes.
    
    Args:
        handoff_doc_path: Path to the handoff documentation
        delegation_target: Target agent for delegation
        risk_tier: Optional risk tier override
        
    Returns:
        GateReport with validation results
    """
    doc_path = Path(handoff_doc_path)
    
    # Validate handoff document
    validation = validate_handoff_document(doc_path)
    if not validation["valid"]:
        return GateReport(
            status="FAILED",
            message=f"Handoff document validation failed: {validation['error'] or 'Missing required sections'}",
            details={
                "missing_sections": validation["missing_sections"],
                "validation_error": validation["error"]
            }
        )
    
    try:
        # Infer risk tier if not provided
        if risk_tier is None:
            risk_tier = infer_risk_tier(doc_path.read_text())
        
        # Build delegation contract
        delegation_contract = build_delegation_contract(
            source_agent="handoff_gate",
            target_agent=delegation_target,
            risk_tier=risk_tier,
            context={"handoff_doc": str(doc_path)}
        )
        
        # Validate delegation contract
        contract_validation = validate_delegation_contract(delegation_contract)
        if not contract_validation["valid"]:
            return GateReport(
                status="FAILED",
                message="Delegation contract validation failed",
                details={
                    "contract_errors": contract_validation.get("errors", []),
                    "delegation_contract": delegation_contract
                }
            )
        
        # Collect trading policy metrics
        policy_metrics = collect_trading_policy_ab_metrics(DEFAULT_POLICY_DOC_PATHS)
        
        # Write metrics to audit trail
        metrics_path = REPO_ROOT / "data" / "audit" / f"handoff_metrics_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
        write_trading_policy_ab_metrics(policy_metrics, str(metrics_path))
        
        # Append to handoff audit record
        audit_record = {
            "timestamp": datetime.now().isoformat(),
            "source_agent": "handoff_gate",
            "target_agent": delegation_target,
            "risk_tier": risk_tier,
            "handoff_doc": str(doc_path),
            "delegation_contract": delegation_contract,
            "policy_metrics": policy_metrics,
            "status": "SUCCESS"
        }
        
        append_handoff_audit_record(audit_record)
        
        return GateReport(
            status="SUCCESS",
            message=f"Agent handoff gate passed successfully. Risk tier: {risk_tier}",
            details={
                "risk_tier": risk_tier,
                "delegation_contract": delegation_contract,
                "policy_metrics": policy_metrics,
                "metrics_path": str(metrics_path)
            }
        )
        
    except Exception as e:
        logging.error(f"Error in agent handoff gate: {e}")
        return GateReport(
            status="ERROR",
            message=f"Unexpected error during handoff gate processing: {str(e)}",
            details={"exception": str(e)}
        )


def main():
    """CLI entry point for the agent handoff gate."""
    parser = argparse.ArgumentParser(
        description="Validate and process agent handoff documentation"
    )
    parser.add_argument(
        "handoff_doc",
        help="Path to the handoff documentation file"
    )
    parser.add_argument(
        "--target-agent",
        default="trading_agent",
        help="Target agent for delegation (default: trading_agent)"
    )
    parser.add_argument(
        "--risk-tier",
        choices=["low", "medium", "high", "critical"],
        help="Override risk tier assessment"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose output"
    )
    
    args = parser.parse_args()
    
    if args.verbose:
        logging.basicConfig(level=logging.INFO)
    
    # Run the handoff gate
    report = run_agent_handoff_gate(
        handoff_doc_path=args.handoff_doc,
        delegation_target=args.target_agent,
        risk_tier=args.risk_tier
    )
    
    # Output results
    print(f"Status: {report.status}")
    print(f"Message: {report.message}")
    
    if args.verbose and report.details:
        print("\nDetails:")
        for key, value in report.details.items():
            print(f"  {key}: {value}")
    
    # Exit with appropriate code
    sys.exit(0 if report.status == "SUCCESS" else 1)


if __name__ == "__main__":
    main()