#!/usr/bin/env python3
"""
Check for consecutive trade skips across multiple days.
Used by GitHub Actions to alert when all recent days show SKIP actions.
"""

import json
import sys
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional


def load_trades_for_date(date_str: str, data_dir: Path) -> Optional[list[dict]]:
    """Load trade data for a specific date."""
    trade_file = data_dir / f"trades_{date_str}.json"

    if not trade_file.exists():
        return None

    try:
        with open(trade_file) as f:
            data = json.load(f)
            # Ensure it's a list
            if not isinstance(data, list):
                print(f"Warning: {trade_file} does not contain a list", file=sys.stderr)
                return None
            return data
    except (OSError, json.JSONDecodeError) as e:
        print(f"Error loading {trade_file}: {e}", file=sys.stderr)
        return None


def check_for_skips(trades: list[dict]) -> dict:
    """
    Check if any trades in the list are SKIPs.
    Returns dict with skip info or None if no skips found.
    """
    if not trades:
        return None

    for trade in trades:
        if trade.get('action') == 'SKIP':
            result = {
                'date': trade.get('date', 'unknown'),
                'skip_reason': trade.get('skip_reason', 'No reason provided'),
                'strategy': trade.get('strategy', 'unknown'),
                'strategy_version': trade.get('strategy_version', 'unknown'),
                'trend_analysis': trade.get('trend_analysis', {}),
                'rsi_values': {}
            }

            # Extract RSI values if available
            trend_analysis = trade.get('trend_analysis', {})
            for symbol, data in trend_analysis.items():
                if 'rsi' in data:
                    result['rsi_values'][symbol] = data['rsi']

            return result

    return None


def format_ma_distance(trend_data: dict) -> str:
    if not trend_data:
        return "N/A"

    price = trend_data.get('price', 0)
    ma50 = trend_data.get('ma50', 0)
    pct = trend_data.get('pct', 0)
    above = trend_data.get('above', False)

    status = "above" if above else "below"
    return f"${price:.2f} ({pct:+.2f}% {status} MA50 ${ma50:.2f})"


def format_issue_body(skip_days: list[dict]) -> str:
    """Format GitHub issue body with skip information."""
    body_lines = [
        "## Trade Skip Alert",
        "",
        f"**Alert**: All trades were skipped for the last {len(skip_days)} consecutive days.",
        "",
        "### Skip Summary",
        ""
    ]

    for skip_info in reversed(skip_days):  # Most recent first
        date = skip_info['date']
        reason = skip_info['skip_reason']
        strategy = skip_info['strategy']
        version = skip_info['strategy_version']

        body_lines.extend([
            f"#### {date}",
            f"- **Strategy**: {strategy} v{version}",
            f"- **Reason**: {reason}",
            ""
        ])

        # Add trend analysis if available
        trend_analysis = skip_info.get('trend_analysis', {})
        if trend_analysis:
            body_lines.append("**Market Position vs 50-day MA:**")
            for symbol, data in sorted(trend_analysis.items()):
                body_lines.append(f"- **{symbol}**: {format_ma_distance(data)}")
            body_lines.append("")

        # Add RSI values if available
        rsi_values = skip_info.get('rsi_values', {})
        if rsi_values:
            body_lines.append("**RSI Values:**")
            for symbol, rsi in sorted(rsi_values.items()):
                body_lines.append(f"- **{symbol}**: {rsi:.2f}")
            body_lines.append("")

    body_lines.extend([
        "---",
        "",
        "### Action Items",
        "",
        "- [ ] Review current market conditions",
        "- [ ] Verify strategy parameters are appropriate",
        "- [ ] Check if MA thresholds need adjustment",
        "- [ ] Consider manual intervention if needed",
        "",
        "**Generated by**: `.github/workflows/monitor-trade-skips.yml`"
    ])

    return "\n".join(body_lines)


def main():
    """Main execution function."""
    # Configuration
    data_dir = Path(__file__).parent.parent / "data"
    days_to_check = 3

    # Ensure data directory exists
    if not data_dir.exists():
        print(f"Error: Data directory not found: {data_dir}", file=sys.stderr)
        sys.exit(2)

    # Calculate dates to check (excluding today)
    today = datetime.now().date()
    dates_to_check = [(today - timedelta(days=i)).strftime('%Y-%m-%d')
                      for i in range(1, days_to_check + 1)]

    print(f"Checking for consecutive skips in: {', '.join(dates_to_check)}")

    # Check each day for skips
    skip_days = []
    for date_str in dates_to_check:
        trades = load_trades_for_date(date_str, data_dir)

        if trades is None:
            print(f"⚠️  No trade data for {date_str}")
            continue

        skip_info = check_for_skips(trades)
        if skip_info:
            print(f"✓ {date_str}: SKIP detected - {skip_info['skip_reason']}")
            skip_days.append(skip_info)
        else:
            print(f"✗ {date_str}: No skips (trades executed)")

    # Check if all checked days had skips
    if len(skip_days) >= days_to_check:
        print(f"\n🚨 ALERT: All {days_to_check} consecutive days had SKIP actions!")

        # Output issue body for GitHub Actions
        issue_body = format_issue_body(skip_days)

        # Write to file for GitHub Actions to read
        output_file = Path("/tmp/skip_alert_body.txt")  # noqa: S108 - CI output file
        output_file.write_text(issue_body)

        print(f"\nIssue body written to: {output_file}")
        print("\nIssue preview:")
        print("=" * 80)
        print(issue_body)
        print("=" * 80)

        # Exit with code 1 to signal alert condition
        sys.exit(1)
    else:
        print(f"\n✅ No consecutive skips detected ({len(skip_days)}/{days_to_check} days had skips)")
        sys.exit(0)


if __name__ == "__main__":
    main()
