#!/usr/bin/env python3
"""
Publish Weekend Learning Summary to Dev.to

This script generates and publishes a weekend learning summary post to Dev.to.
It summarizes:
- RAG lessons learned this week
- YouTube content ingested
- Trading insights generated
- Preparation for Monday trading
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path

import requests


def get_devto_api_key() -> str | None:
    """Get Dev.to API key from environment."""
    return os.environ.get("DEVTO_API_KEY")


def count_lessons_this_week() -> int:
    """Count lessons learned files from this week."""
    lessons_dir = Path("rag_knowledge/lessons_learned")
    if not lessons_dir.exists():
        return 0

    count = 0
    cutoff = datetime.now().timestamp() - (7 * 24 * 60 * 60)  # 7 days ago

    for f in lessons_dir.glob("*.md"):
        if f.stat().st_mtime > cutoff:
            count += 1

    return count


def get_weekend_insights() -> dict:
    """Load weekend insights if available."""
    insights_file = Path("data/weekend_insights.json")
    if insights_file.exists():
        try:
            return json.loads(insights_file.read_text())
        except Exception:
            pass
    return {}


def get_portfolio_status() -> dict:
    """Get current portfolio status."""
    state_file = Path("data/system_state.json")
    if state_file.exists():
        try:
            data = json.loads(state_file.read_text())
            return {
                "equity": data.get("portfolio", {}).get("equity", "N/A"),
                "positions": data.get("paper_account", {}).get("positions_count", 0),
            }
        except Exception:
            pass
    return {"equity": "N/A", "positions": 0}


def generate_weekend_post() -> tuple[str, str]:
    """Generate the weekend learning blog post content."""
    today = datetime.now()
    day_name = today.strftime("%A")
    date_str = today.strftime("%B %d, %Y")

    # Calculate day number (from Oct 31, 2025 start)
    start_date = datetime(2025, 10, 31)
    day_number = (today - start_date).days

    lessons_count = count_lessons_this_week()
    insights = get_weekend_insights()
    portfolio = get_portfolio_status()

    title = f"AI Trading: Weekend Learning Report | Day {day_number} - {date_str}"

    recommendations = insights.get("recommendations", [
        "Continue following Phil Town Rule #1 principles",
        "Focus on credit spreads with defined risk",
        "Monitor VIX for optimal entry timing",
    ])

    next_actions = insights.get("next_actions", [
        "Review Monday pre-market conditions",
        "Check SPY options chain for opportunities",
        "Verify position sizes align with 5% max risk",
    ])

    body = f"""---
title: "{title}"
published: true
description: "Weekend learning and preparation for AI Trading System - Day {day_number}/90"
tags: trading, ai, machinelearning, investing
series: "AI Trading Journey"
canonical_url: https://igorganapolsky.github.io/trading/
---

## Weekend Learning Summary

**Day {day_number}/90** | {day_name}, {date_str}

Markets are closed, but learning never stops. Here's what the AI Trading System learned this weekend.

### Portfolio Status
- **Equity**: ${portfolio['equity']}
- **Open Positions**: {portfolio['positions']}
- **Strategy**: SPY Credit Spreads (30-45 DTE)

### This Week's Learning

**Lessons Recorded**: {lessons_count} new lessons in RAG

**Content Ingested**:
- Phil Town YouTube videos (Rule #1 Investing)
- Options education (credit spreads, risk management)
- Trading blogs and podcasts

### Key Insights

**Recommendations for Next Week**:
{chr(10).join(f"- {r}" for r in recommendations)}

**Monday Action Items**:
{chr(10).join(f"- {a}" for a in next_actions)}

### Phil Town Alignment Check

Every trade must pass the Rule #1 filter:
1. **Meaning** - Understand the business (SPY = S&P 500)
2. **Moat** - Competitive advantage (market-leading companies)
3. **Management** - Quality leadership (diversified exposure)
4. **Margin of Safety** - Buy at attractive prices (30-delta spreads)

### North Star Progress

**Goal**: $100/day from $50K account (2.5-3 years)
**Current**: Building foundation with $5K paper account
**Strategy**: Credit spreads → 80%+ win rate → compound gains

---

*This post was auto-generated by the AI Trading System's weekend learning pipeline.*
*CTO: Claude Opus 4.5 | CEO: Igor Ganapolsky*

[View Dashboard](https://igorganapolsky.github.io/trading/) | [GitHub](https://github.com/IgorGanapolsky/trading)
"""

    return title, body


def publish_to_devto(title: str, body: str) -> str | None:
    """Publish article to Dev.to and return URL."""
    api_key = get_devto_api_key()
    if not api_key:
        print("No DEVTO_API_KEY found")
        return None

    headers = {
        "api-key": api_key,
        "Content-Type": "application/json",
    }

    payload = {
        "article": {
            "title": title,
            "body_markdown": body,
            "published": True,
            "series": "AI Trading Journey",
            "tags": ["trading", "ai", "machinelearning", "investing"],
        }
    }

    try:
        response = requests.post(
            "https://dev.to/api/articles",
            headers=headers,
            json=payload,
            timeout=30,
        )

        if response.status_code == 201:
            data = response.json()
            url = data.get("url", "")
            print(f"Published to Dev.to: {url}")
            return url
        else:
            print(f"Dev.to API error: {response.status_code}")
            print(response.text)
            return None

    except Exception as e:
        print(f"Dev.to publish failed: {e}")
        return None


def main():
    """Main entry point."""
    print("=" * 60)
    print("Weekend Learning -> Dev.to Publisher")
    print("=" * 60)

    title, body = generate_weekend_post()
    print(f"\nGenerated post: {title}")
    print(f"Body length: {len(body)} characters")

    url = publish_to_devto(title, body)

    if url:
        print(f"\n✅ Successfully published: {url}")
        return 0
    else:
        print("\n❌ Failed to publish to Dev.to")
        return 1


if __name__ == "__main__":
    sys.exit(main())
