name: CI
on: [push, pull_request]
jobs:
  trunk-check:
    name: Trunk Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          trunk_token: ${{ secrets.TRUNK_API_TOKEN }}
